const TeamImages ={
    img0: require('./teamimages/img0.jpeg'),
    img1: require('./teamimages/img1.jpeg'),
    img2: require('./teamimages/img2.jpg'),
    img3: require('./teamimages/img3.jpg'),
    img4: require('./teamimages/img4.jpeg'),
    img5: require('./teamimages/img5.jpg'),
    img6: require('./teamimages/img6.jpg'),
    img7: require('./teamimages/img7.jpeg'),
    img8: require('./teamimages/img8.jpeg'),
    img9: require('./teamimages/img9.jpg'),
    img10: require('./teamimages/img10.jpeg'),
    img11: require('./teamimages/img11.jpg'),
    img12: require('./teamimages/img12.jpg'),
    img13: require('./teamimages/img13.jpg'),
    img14: require('./teamimages/img14.jpg'),
    img15: require('./teamimages/img15.jpg'),
    img16: require('./teamimages/img16.jpg'),
    img17: require('./teamimages/img17.jpg'),
    img18: require('./teamimages/img18.jpg'),
    img19: require('./teamimages/img19.jpg'),
    img20: require('./teamimages/img20.jpg'),
    img21: require('./teamimages/img21.jpg'),
    img22: require('./teamimages/img22.jpg'),
    img23: require('./teamimages/img23.jpg'),
    img24: require('./teamimages/img24.jpeg'),
    img25: require('./teamimages/img25.jpg'),
    img26: require('./teamimages/img26.jpg'),
    img27: require('./teamimages/img27.jpg'),
    img28: require('./teamimages/img28.jpeg'),
    img29: require('./teamimages/img29.jpg'),
    img30: require('./teamimages/img30.jpeg'),
    img31: require('./teamimages/img31.jpg'),
    img32: require('./teamimages/img32.jpg'),
    quotation: require('./teamimages/quotation.png'),
}
export default TeamImages;